trigger: 
  - feature/*
  - main

pool: infra

variables:
  workDir: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage: Build
  displayName: infralogin
  jobs:       
  - job: TerraformInitPlanApply
    displayName: Terraform Init Plan Apply Job
    steps: 

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'amit'
        backendAzureRmStorageAccountName: 'vmstorageal'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'amit'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(workDir)
        environmentServiceNameAzureRM: 'amit'
        additionalArgs: '-auto-approve'
